### ISSUE TITLE
Did I do something wrong? How can I fix this?

### ISSUE THREAD

**Issue by Arthurfogo7** [strato-emu/strato#10]
![image](https://github.com/strato-emu/strato/assets/85951083/ec0d7904-0322-417a-9637-755e1c1af725)

**Comment by TheASVigilante** [comment]
Check the building guide, it has your solution.

**Comment by Crytonics** [comment]
https://github.com/strato-emu/strato/blob/master/BUILDING.md

**Comment by beloncode** [comment]
Are you fixed the problem? Otherwise, enables symbolic link construction globally, using ```git config --global core.symlinks true``` and rerun with ```git submodule foreach git config core.symlinks true```, if doesn't fixes it, try to re-clone the complete repository with all dependencies (submodules) with ``` git clone --recursive https://github.com/strato-emu/strato.git``` again

**Comment by TheASVigilante** [comment]
I'm just going to assume you fixed this
