### ISSUE TITLE
Bioshock 2

### ISSUE THREAD

**Issue by Gamelover7825** [strato-emu/strato#144]
Game runs pretty well (less demanding on the hardware than the 1st part) but when saving ingame progress it says not enough memory.

**Comment by lynxnb** [comment]
@dima-xd something to look into since you're working on VFS

**Comment by Crytonics** [comment]
Closing because we have repository for game-specific issues, go to the [Strato's Compatibility List](https://github.com/strato-emu/compat-list) and report the issue there.
