### ISSUE TITLE
Cuphead crash on Mediatek helio G serie

### ISSUE THREAD

**Issue by EderNX** [strato-emu/strato#145]
the game runs at a good frame rate but the game crashes during gameplay.

**Comment by Intelparcel** [comment]
When will the game crash? And what version of skyline are you using? It seems that you have the same issue as mine

**Comment by EderNX** [comment]
the last version of edge where it worked well is v29 I think, in more recent versions it doesn't open, although in v29 the game closed too, I use skyline edge v69, my phone has 8gb of ram and a helio g95

**Comment by Intelparcel** [comment]
> the last version of edge where it worked well is v29 I think, in more recent versions it doesn't open, although in v29 the game closed too, I use skyline edge v69, my phone has 8gb of ram and a helio g95
Oh, I think that's from CPU, although your chip is good but...usually Mediatek and any other chips(like Exynos) performs worse than Snapdragon's chips. Mine's issue is kinda related to memory(I think?). My phone have a Snapdragon 835 SoC and with only 4gb , I can play almost every bosses, the only problem is that the game crashed when I play the "One hell in a time" battle, after talking to the devil the game freezes and crashed. You can try changing some settings, like enable "force maximum GPU clocks", disable "Use docked mode", enable "Fast GPU readback", test each settings for each version(for the latest version and the version that you said that worked best)

**Comment by EderNX** [comment]
After v29 most 2d games don't open for me, like undertale, deltarune, rivals of aether and cuphead.

**Comment by Intelparcel** [comment]
> After v29 most 2d games don't open for me, like undertale, deltarune, rivals of aether and cuphead.

Have you tried tweaking some settings I mentioned in my last comment?

> > 
>  You can try changing some settings, like enable "force maximum GPU clocks", disable "Use docked mode", enable "Fast GPU readback", disable "Use direct memory import"(if you accidentally enabled it). Test each settings for each version(for the latest version and the version that you said that worked best). Hope that helps

**Comment by Pepepepepeps1212e8** [comment]
> > the last version of edge where it worked well is v29 I think, in more recent versions it doesn't open, although in v29 the game closed too, I use skyline edge v69, my phone has 8gb of ram and a helio g95
> 
> Oh, I think that's from CPU, although your chip is good but...usually Mediatek and any other chips(like Exynos) performs worse than Snapdragon's chips in Skyline. Mine's issue is kinda related to memory(I think?). My phone have a Snapdragon 835 SoC and with only 4gb , I can play almost every bosses, except the "One hell in a time" battle, after talking to the devil the game freezes and crashed. You can try changing some settings, like enable "force maximum GPU clocks", disable "Use docked mode", enable "Fast GPU readback", disable "Use direct memory import"(if you accidentally enabled it). Test each settings for each version(for the latest version and the version that you said that worked best). Hope that helps

The same thing happens to me, I have a snapdragon 845 and 4 ram. He let me fight all the bosses in the game, but specifically the battle against the devil is where he won't let me play.

**Comment by boludoz** [comment]
> the game runs at a good frame rate but the game crashes during gameplay.

Same on Exynos 990, a bit old but works.

**Comment by boludoz** [comment]
> > the last version of edge where it worked well is v29 I think, in more recent versions it doesn't open, although in v29 the game closed too, I use skyline edge v69, my phone has 8gb of ram and a helio g95
> 
> Oh, I think that's from CPU, although your chip is good but...usually Mediatek and any other chips(like Exynos) performs worse than Snapdragon's chips in Skyline. Mine's issue is kinda related to memory(I think?). My phone have a Snapdragon 835 SoC and with only 4gb , I can play almost every bosses, except the "One hell in a time" battle, after talking to the devil the game freezes and crashed. You can try changing some settings, like enable "force maximum GPU clocks", disable "Use docked mode", enable "Fast GPU readback", disable "Use direct memory import"(if you accidentally enabled it). Test each settings for each version(for the latest version and the version that you said that worked best). Hope that helps

Direct memory import only works in Adreno

**Comment by Intelparcel** [comment]
> > > the last version of edge where it worked well is v29 I think, in more recent versions it doesn't open, although in v29 the game closed too, I use skyline edge v69, my phone has 8gb of ram and a helio g95
> > 
> > 
> > Oh, I think that's from CPU, although your chip is good but...usually Mediatek and any other chips(like Exynos) performs worse than Snapdragon's chips in Skyline. Mine's issue is kinda related to memory(I think?). My phone have a Snapdragon 835 SoC and with only 4gb , I can play almost every bosses, except the "One hell in a time" battle, after talking to the devil the game freezes and crashed. You can try changing some settings, like enable "force maximum GPU clocks", disable "Use docked mode", enable "Fast GPU readback", disable "Use direct memory import"(if you accidentally enabled it). Test each settings for each version(for the latest version and the version that you said that worked best). Hope that helps
> 
> Direct memory import only works in Adreno, the screen will go black.

Edited, thanks for pointing that out :)

**Comment by Crytonics** [comment]
Closing because we have repository for game-specific issues, go to the [Strato's Compatibility List](https://github.com/strato-emu/compat-list) and report the issue there.
