### ISSUE TITLE
Shin Megami Tensei 3 HD Remaster issues

### ISSUE THREAD

**Issue by ktheticdev** [strato-emu/strato#162]
Some of the textures won't render, and the game runs incorrectly, too. 
![Screenshot_20230813-143028](https://github.com/strato-emu/strato/assets/64607352/0bf4598a-e8c8-414c-9e56-4fc1b46f472a)

**Comment by Crytonics** [comment]
Closing because we have repository for game-specific issues, go to the [Strato's Compatibility List](https://github.com/strato-emu/compat-list) and report the issue there.
