### ISSUE TITLE
Built-in vibration does not work

### ISSUE THREAD

**Issue by xwpd** [strato-emu/strato#169]
I played several games with vibrations, and my phone has built-in vibrations, which are also set to enable, but they all won't vibrate.

**Comment by Crytonics** [comment]
What phone do you have, can you link your phone on [GSMArena](https://www.gsmarena.com/).

**Comment by xwpd** [comment]
Phone: xiaomi redmi note 12 turbo 16g+1T   https://www.gsmarena.com/xiaomi_redmi_note_12_turbo-12181.php
Games: Ultimate Fishing Simulator 、Need for Speed:Hot Pursuit

**Comment by Crytonics** [comment]
Yea rn, vibrations doesn't work as it should.

**Comment by lynxnb** [comment]
The issue should be fixed as of commit `74173a39`.
