### ISSUE TITLE
shader_compiler/runtime_info.h file not found

### ISSUE THREAD

**Issue by Nye69** [strato-emu/strato#17]
In file included from C:/Users/strato/app/src/main/cpp/skyline/gpu/interconnect/maxwell_3d/packed_pipeline_state.cpp:7:
C:/Users/strato/app/src/main/cpp/skyline/gpu/interconnect/maxwell_3d/packed_pipeline_state.h:8:10: fatal error: 'shader_compiler/runtime_info.h' file not found
#include <shader_compiler/runtime_info.h>

**Comment by lynxnb** [comment]
https://github.com/strato-emu/strato/blob/master/BUILDING.md
