### ISSUE TITLE
Aferimage not start problem

### ISSUE THREAD

**Issue by Darkherman** [strato-emu/strato#176]
Afterimage sometimes starts and sometimes does not and does not respond to controls.

Look check https://youtu.be/-iYJSaewaEo?si=VIErgGvJ-5iWIHTX

**Comment by Crytonics** [comment]
Try set Input controller from "Handheld + Pro Controller" to "Pro Controller" in settings.

Also this is not the right repository to report game-specific issues, go to the [Strato's Compatibility List](https://github.com/strato-emu/compat-list) and report the issue there.

**Comment by Darkherman** [comment]
> Try set Input controller from "Handheld + Pro Controller" to "Pro Controller" in settings.
> 
> Also this is not the right repository to report game-specific issues, go to the [Strato's Compatibility List](https://github.com/strato-emu/compat-list) and report the issue there.

I tried it but nothing remains the same and it does not respond to the remote control either.

**Comment by Crytonics** [comment]
> > Try set Input controller from "Handheld + Pro Controller" to "Pro Controller" in settings.
> > Also this is not the right repository to report game-specific issues, go to the [Strato's Compatibility List](https://github.com/strato-emu/compat-list) and report the issue there.
> 
> I tried it but nothing remains the same and it does not respond to the remote control either.

Create issue in [Strato's Compatibility List](https://github.com/strato-emu/compat-list).
