### ISSUE TITLE
I want to become a simulator developer.

### ISSUE THREAD

**Issue by jcZhou-615** [strato-emu/strato#18]
I am a high school student and I want to become a simulator developer. Could you provide a learning path for me?Alternatively, could you recommend some books?

**Comment by RedCoder09** [comment]
I don't know why you're asking about this in the issues section of a GitHub repo for an Android Nintendo Switch emulator, but I can recommend learning how to use a game engine like Godot and Unity.

**Comment by jcZhou-615** [comment]
I think it's cool to be able to make a simulator for switch, and I want to be able to make this simulator, but I don't know how to learn it, I should master that knowledge, so I asked for help here. Thank you so much if you could teach me how to use Godot and Unity

**Comment by Jack-Rickwood** [comment]
Here's one path:

You should first learn a low level object oriented programming language like C++ or Rust. Try to write a Chip-8 emulator (or something similarly simple) in it, and from there you can move on to more complex systems like the Gameboy, NES, or even a simple 3D console like the N64. Begin to optimize some of these toy emulators that you write - maybe try implementing a JIT, or depending on the system, you could maybe even try to mess with some AOT compilation.

Once you have a good understanding of how emulation works conceptually, learn a graphics API like OpenGL (you'll want to learn Vulkan eventually if you want to help with Strato, but starting with OpenGL might be more interesting to start with). Get comfortable with it through a project like a game engine. From there you can start to contribute to open source, modern console emulators.

But really just pick something related to emulation and learn it, preferably through some type of project. As you gain more experience as a programmer, the path (and where you lack knowledge) should become clear.

**Comment by jcZhou-615** [comment]
Thank you so much. Good people have a safe life.
![-c2e8c955c38053e.jpg](https://s2.loli.net/2023/05/17/ruF7wxKcLaoifvN.jpg)
