### ISSUE TITLE
Missing Processing Effects

### ISSUE THREAD

**Issue by Andeer21** [strato-emu/strato#181]
Some games do not have lighting and shadow effects
![Screenshot_20230910-201926](https://github.com/strato-emu/strato/assets/94584792/53c25edd-1bc2-4413-8553-37d155d69fcf)
![Screenshot_20230910-201450](https://github.com/strato-emu/strato/assets/94584792/0af3e577-2d8a-4f33-be3e-0fcc55aa922a)
![Screenshot_20230910-201108](https://github.com/strato-emu/strato/assets/94584792/34192891-eaff-4115-a042-114642e1b98c)

**Comment by Crytonics** [comment]
This is not the right repository to report game-specific issues, go to the [Strato's Compatibility List](https://github.com/strato-emu/compat-list) and report the issue there.
