### ISSUE TITLE
Built-in Keyboard Doesn't Work In Many Devices 

### ISSUE THREAD

**Issue by Ishan0981** [strato-emu/strato#185]
Built-in Keyboard Doesn't Work In Many Devices Please Fix This Problem

**Comment by Crytonics** [comment]
Can you give more information. What game, device etc...

**Comment by Intelparcel** [comment]
Duplication of #190 issue. Close one?

**Comment by Crytonics** [comment]
As i can see you create new issue with same issue using unofficial build #190 . We don't provide support for unofficial builds. So i am closing this issue.
