### ISSUE TITLE
[Request] Computer version.

### ISSUE THREAD

**Issue by boludoz** [strato-emu/strato#187]
This emulator is so good that it deserves a version for Windows/Linux.

**Comment by beloncode** [comment]
It's a good idea! but the emulator is designed for Android; I don't believe this will happen one day, or that it's even possible (or necessary)

**Comment by boludoz** [comment]
Yuzu doesn't even work on my Exynos, Skyline at least starts.

**Comment by beloncode** [comment]
Indeed, but we already have Yuzu running on the Desktop, and Strato is specifically optimized for mobile devices with Adreno and Mali GPUs! I recommend opening an issue in the Yuzu Android project to address this problem

**Comment by boludoz** [comment]
It would be necessary to evaluate if the effort is necessary and what the main differences are with Yuzu and if it is really worth it.

**Comment by boludoz** [comment]
> Indeed, but we already have Yuzu running on the Desktop, and Strato is specifically optimized for mobile devices with Adreno and Mali GPUs! I recommend opening an issue in the Yuzu Android project to address this problem

I think the problem is the direct memory import.

**Comment by Crytonics** [comment]
This project is for android only.
