### ISSUE TITLE
[Detail] robin-hood it is good and efficient hash, but it takes up too much memory

### ISSUE THREAD

**Issue by boludoz** [strato-emu/strato#188]
Instead I recommend testing with https://github.com/Tessil/sparse-map.git which is efficient with memory usage, ideal for mobile devices.

**Comment by boludoz** [comment]
https://github.com/Tessil/hopscotch-map is a middle point

**Comment by boludoz** [comment]
![image](https://github.com/strato-emu/strato/assets/11653030/89bd740e-9a03-4837-9826-4f7ec42ab8ef)

**Comment by bylaws** [comment]
![https://media.tenor.com/pyewWa63HMkAAAAM/head-funny.gif](https://media.tenor.com/pyewWa63HMkAAAAM/head-funny.gif)

**Comment by lynxnb** [comment]
We will only take this issue seriously if proper runtime profiling of the emulator is performed. 
We will look into an alternative has map only once evidence of the high memory usage coming exclusively from the hash map is supplied.

**Comment by boludoz** [comment]
> We will only take this issue seriously if proper runtime profiling of the emulator is performed. We will look into an alternative has map only once evidence of the high memory usage coming exclusively from the hash map is supplied.

No, at no point did I say that it would be a good idea to replace it, just see if it is possible to provide more alternatives, perhaps it would only be useful to replace it in "shader-compiler".
