### ISSUE TITLE
Pokemon Let's Go Pikachu Black Screen 

### ISSUE THREAD

**Issue by Ishan0981** [strato-emu/strato#189]
Pokemon Let's Go Pikachu Black Screen On The Cutscene. After Cutscene Game Started But On The Cutscene Appear Black Screen. Fix This Problem
Processor: Dimensity 8050

**Comment by Crytonics** [comment]
This is not the right repository to report game-specific issues, go to the [Strato's Compatibility List](https://github.com/strato-emu/compat-list) and report the issue there.
