### ISSUE TITLE
[Request] Add resolution down and upscale or/and ASTC texture compression

### ISSUE THREAD

**Issue by boludoz** [strato-emu/strato#191]
Add resolution downscale and upscale of textures.

**Comment by lynxnb** [comment]
We might do this in the future, but it won't help with performance at all. Downscaling textures has no benefits on performance, while upscaling them will increase rendering time.

**Comment by boludoz** [comment]
> We might do this in the future, but it won't help with performance at all. Downscaling textures has no benefits on performance, while upscaling them will increase rendering time.

Does ASTC texture compression improve performance?

**Comment by TheASVigilante** [comment]
@boludoz It's mainly intended to reduce ram usage at the cost of performance

**Comment by boludoz** [comment]
> @boludoz It's mainly intended to reduce ram usage at the cost of performance if you mean it being done at runtime, otherwise the performance cost is null

Could it be implemented? For "older" devices?

**Comment by lynxnb** [comment]
ASTC texture recompression makes little sense on phones, since they natively support ASTC and they don't need to decompress them before using them.
