### ISSUE TITLE
What setting is causing all this?

### ISSUE THREAD

**Issue by RmpSamm** [strato-emu/strato#20]
![Screenshot_20230516_011902](https://github.com/strato-emu/strato/assets/133739201/fbaaca36-13d3-428d-b844-3d8213ad8898)

I had recently downloaded pokemon sword and it was going smoothly. But then I noticed a lot of lags that began to come up like i couldn't control my character without lagging every 5-10 seconds. So then I went on YouTube and watched a video where a guy adjusts his settings, however this video was about 6 months old and because skyline emulator updates frequently its possible that certain settings and their affects have changed, but anyways. I went and began to change some of my settings around according to the video as much as possible however after I completed the changes everytime I played the game my screen was like this. I'm not very technical and I'm amongst the poorest in terms of knowledge in this technical field, please assist me and thank you very much.

**Comment by Synz123** [comment]
wdym downloaded? from a site?

**Comment by ArbestRiAgain** [comment]
😖

**Comment by Gsxrpitts61** [comment]
I've had the same issue.  I have sd888.  I don't believe it's any of the settings or drivers.   Just the game.  Idk

**Comment by AndresNorm** [comment]
Piracy Spotted

Close this now

**Comment by ArbestRiAgain** [comment]
Close this issue
