### ISSUE TITLE
Darkwood Text Missing 

### ISSUE THREAD

**Issue by TheMercenary333** [strato-emu/strato#202]
Game Behaviour

- New game settings UI, loding screen and in game texts are missing.

![Screenshot_20230507_011821.jpg](https://user-images.githubusercontent.com/74915480/236648640-a539c90f-f4cf-473b-addb-bb0e6a721972.jpg)

![Screenshot_20230507_005913.jpg](https://user-images.githubusercontent.com/74915480/236648643-099a8a01-64ef-4d23-8c6a-bc4c4e361502.jpg)

![Screenshot_20230507_010255.jpg](https://user-images.githubusercontent.com/74915480/236648646-ac913d8a-3192-4a71-b735-252f27f10a3e.jpg)

**Comment by Crytonics** [comment]
This is not the right repository to report game-specific issues, go to the [Strato's Compatibility List](https://github.com/strato-emu/compat-list) and report the issue there.
