### ISSUE TITLE
Save Data Export Is Not Working

### ISSUE THREAD

**Issue by Ishan0981** [strato-emu/strato#206]
When I Click On Export Then Shows Many Apps For Share And I Try To Share In WhatsApp, Discord But In WhatsApp File Is Not Sending And In Discord File Name Showing Unknown But I Try To Send Then My Discord App Is Crashed. Solve This Problem.

**Comment by Crytonics** [comment]
For me it is working fine. Can you upload video where you have problem?

**Comment by Ishan0981** [comment]
I Can't Upload Video Direct In GitHub But Can I Give You The Video Link of Google Drive.

**Comment by Crytonics** [comment]
> @Crytonics I Can't Upload Video Direct In GitHub But Can I Give You The Video Link of Google Drive.

Sure, you can also do in MEGA.

**Comment by Ishan0981** [comment]
Ohhh Lol 😅 I Recently Check I Forgot To Save My Game Because My Save Is Not Extracting Sorry..
