### ISSUE TITLE
Optimization problems 

### ISSUE THREAD

**Issue by CAROLUSANONIM** [strato-emu/strato#217]
So here I'm sorry if I'm not clear in conveying it, but I want to give something that might be able to be fixed for the Strato emulator, namely game optimization problems found in many Chipsets other than Snapdragon such as Helio, maybe Strato can be smoother than Skyline in optimizing games On the other chipset smartphone

**Comment by Andeer21** [comment]
If your device is a potato there's not much you can do

**Comment by Crytonics** [comment]
Snapdragon have some features that others don't, devs are working for optimization but Snapdragon will always be better.
