### ISSUE TITLE
Add option for remove update and add UI interface for update 

### ISSUE THREAD

**Issue by Hariu7** [strato-emu/strato#223]
![Screenshot_20231217_121953_yuzu](https://github.com/strato-emu/strato/assets/151449327/572b80cf-5529-4928-966e-9820493aad73)
I recommend to you to add this UI interface to disable and enable update or Dlc any time and one more thing in emulator like yuzu can't remove update from internal storage only we can disable it . We can detele update from nand folder specific.  Please add add remove update feature this can be done by update file

**Comment by Crytonics** [comment]
They are working on support for update and DLC #160
