### ISSUE TITLE
Add support for virtual Bluetooth gamepad 

### ISSUE THREAD

**Issue by Hariu7** [strato-emu/strato#226]
SOME player want play game with co-op mode . Game like Naruto ultimate ninja storm offer player one and player 2 configuration with two controller so I request you add support for virtual controller. 
Video link:
https://youtu.be/5R7Wcsp3e38?si=J8X_dKhXz2r6NVAc
App link 
https://play.google.com/store/apps/details?id=com.kunkunsoft.gamepadforvr
It is paid but there are many. that free so please add it
PPSSPP offers it video link
https://youtu.be/6lMOYR26cJg?si=krPq88NtiBg5NpBO

**Comment by Hariu7** [comment]
![Uploading Screenshot_20231218_224348_Bluetooth Gamepad.jpg…]()

**Comment by Hariu7** [comment]
![Screenshot_20231218_224348_Bluetooth Gamepad](https://github.com/strato-emu/strato/assets/151449327/ad19fb31-7663-4388-940e-9bc23159149a)

**Comment by Hariu7** [comment]
https://youtu.be/A0Pvq0dQAec?si=7dBxNDCYM2EQay_t

**Comment by Hariu7** [comment]
This can also done by enabling key mapping option

**Comment by lynxnb** [comment]
This should already be doable sincce we support controller mappings, I'm going to close this as this doesn't really require any explicit support from us.
