### ISSUE TITLE
Add Low Resolution Option

### ISSUE THREAD

**Issue by Whitezinho24** [strato-emu/strato#227]
Could you add an option to reduce the resolution for better performance?
A good ideia :)

**Comment by migaTnoemriQ** [comment]
Yes an important setting most of the emulators are missings

**Comment by Ishan0981** [comment]
> Could you add an option to reduce the resolution for better performance? A good ideia :)

they might do this in the future, but it won't help with performance at all. Downscaling textures has no benefits on performance, while upscaling them will increase rendering time.

**Comment by Crytonics** [comment]
As said in #191
