### ISSUE TITLE
To complete your promise 

### ISSUE THREAD

**Issue by Hariu7** [strato-emu/strato#230]
As we we are waiting for 6 to 7 moths for strato release.  As you said we will release before month end and that you post we are again delaying it. We are not going to blame you performance and graphical issue at present in it we want just to test it.we know work is not complete but I request you release it in which stage it is in as you promise.

Please release it

**Comment by Hariu7** [comment]
Skyline release it first apk with it even not boot sonic mania

**Comment by KyiThatTun** [comment]
> Skyline release it first apk with it even not boot sonic mania

Beta test release would be nice

**Comment by Hariu7** [comment]
> > Skyline release it first apk with it even not boot sonic mania
> 
> Beta test release would be nice

Yes

**Comment by TheASVigilante** [comment]
I get what you mean but stuff like this should be discussed on the discord rather than here, the github issue list is for bugs/feature requests.
