### ISSUE TITLE
Add OpenGL ES Or add Vulkan 1.1 Please

### ISSUE THREAD

**Issue by GithubUser559** [strato-emu/strato#236]
For better compatibility With PowerVR GPU On devices like the TCL 40 se

**Comment by Crytonics** [comment]
OpenGL ES is a legacy API that doesn't have the level of control over the host GPU we need for the Switch. It will eventually be discarded by vendors entirely and just implemented using a compatibility layer such as [ANGLE](https://github.com/google/angle) which implements OGLES atop Vulkan, AMD already does so on Android and other vendors will likely follow once they deem it pointless to have to constantly maintain their OGLES drivers.
