### ISSUE TITLE
How do i download this?

### ISSUE THREAD

**Issue by lug1212** [strato-emu/strato#25]
Trying to download on mobile phone but cant find a package

**Comment by darkmaster420** [comment]
Pretty sure you have to build it yourself. Try following the building guide

**Comment by MYSK-D25N** [comment]
You can get a release apk by going to the [Actions page](https://github.com/strato-emu/strato/actions) of the project then looking through the recent build tasks in the list. At the moment the most recent release available there is in [CI 36 ](https://github.com/strato-emu/strato/actions/runs/4985037479), just look at the bottom of the page where it says artifacts and download the apk.
