### ISSUE TITLE
yuzu-emu/sirit/ down 

### ISSUE THREAD

**Issue by steel101** [strato-emu/strato#253]
In . Gitmodules it has https://github.com/yuzu-emu/sirit/ that is down now because yuzu cofe offline so a fork of it at https://github.com/GPUCode/sirit-1 lets the app build

**Comment by steel101** [comment]
What do you mean not planned a fork is needed to build the APK so I was just helping out to be able to build the newest APK

**Comment by Crytonics** [comment]
We can't use yuzu code

**Comment by ikarishinjigao** [comment]
https://github.com/yuzu-mirror/sirit
Perhaps the yuzu-mirror version is a better option. 
I succeeded in building with it.

**Comment by Crytonics** [comment]
@ikarishinjigao no yuzu code tnx.

**Comment by steel101** [comment]
Opened a pull request with the fix.

**Comment by steel101** [comment]
Pull request was accepted so closing this issue now
