### ISSUE TITLE
Is it possible that we use suyu-emu/sirit to replace the original submodule yuzu-emu/sirit?

### ISSUE THREAD

**Issue by fusigi0930** [strato-emu/strato#259]
the suyu-emu that is a fork from yuzu-emu in gitlab, but, it also has a fork in github
https://github.com/suyu-emu, it still under maintenance recently, maybe we can use it to instead of the sirit of yuzu-emu.

**Comment by Crytonics** [comment]
Duplicate of #256

**Comment by fusigi0930** [comment]
yap, I had create a pull request for it before, but it is rejected.
#256

**Comment by steel101** [comment]
> yap, I had done it and created a pull request for it before, but it is rejected #256

So I have many times with different links to. I gave them the original tha yuzu forked them self and they said no fuck them I made a lot of changes to keep the app going and make it better with all of yuzu code that they never added before it went down. I hope they get there asses out of there butt and start listing to people that want to help with project. Fuck them if they want to help
