### ISSUE TITLE
Different devices use different RAM for the same game

### ISSUE THREAD

**Issue by sovervo** [strato-emu/strato#26]
I have two phones. 
The first retroid pocket3+:
Processor: Unisoc Tiger T618, GPU: Mali G52. 

The second one is oppo a5 2020:
Processor: Snapdragon 665
GPU: Adreno 610.

Bastion game on oppo takes 1000mb of RAM. On retroid 2400mb on startup. Why so? There is a feeling that on retroid the RAM is constantly filled but not released. Because some games crash when it reaches 3000mb. But if you load the save, the RAM will be filled to about 2500mb

**Comment by lynxnb** [comment]
There's no way one would get a lower RAM utilization that the other from Strato itself. The difference is either in the monitoring software, or in the device drivers. In both cases, nothing that we can control directly, apart from generally improving the emulator.

On the other hand, those are both very low spec devices, and we don't officially support them. You won't get any decent performance out of any of those.
