### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by Jariz24** [strato-emu/strato#279]
When do you release the emulator?

**Comment by mhasterlyn14** [comment]
When is the release date?

**Comment by WhaleofGluttony** [comment]
there is no release date yet.

**Comment by user18081972** [comment]
> there is no release date yet.

"We are happy to announce that Strato is set to release in the first half of 2024!" - [Feb 19, 2024](https://strato-emu.github.io/posts/progress-report-feb-2024/)
