### ISSUE TITLE
Discord link redirect to skyline discord server 

### ISSUE THREAD

**Issue by CharlyM1ni** [strato-emu/strato#29]
On the read.md when clicking on the discord link (the one in the contact section) it invite you to skyline's server, I don't know if this was intended or not.

**Comment by unclamped** [comment]
They don't? They point to Strato for me

**Comment by CharlyM1ni** [comment]
It invited me to the skyline discord only on the contact section.
  
  
  
  
>

**Comment by TheASVigilante** [comment]
Points to Strato for me
