### ISSUE TITLE
🥹Please update version number add🥹, fake Skyline v74 very bad👎 =real v69

### ISSUE THREAD

**Issue by MehmetDEDEOGLU** [strato-emu/strato#31]
🥺Could you please add the update version number so that it can be seen inside the application and even in the release notes because there were even Skyline v73 in the forums, the fraudsters changed their name and presented them with the logic on our site first, I think the release notes are also important, it is easy to upgrade and show the version with the APK editor, please I would be very pleased if you take the precaution 🥹

**Comment by CharlyM1ni** [comment]
Please close this.
