### ISSUE TITLE
Friend-play features

### ISSUE THREAD

**Issue by Intelparcel** [strato-emu/strato#35]
So I've been thinking about this quite a long time
Can you guys make a feature that can streams game on the main phone to others phone, like Steam Remote-play but instead we use 5 random characters(contains both letters and numbers) code that is generated from the main phone(if use WiFi) or use device pairing(if use Bluetooth)
After the others phone connected to the main phone, it's still can use its own on-screen controller
It would be very convenient if these features are implemented to the app
[English is my second language so i'm pretty sure there are grammar mistakes here, hope you guys can understand]

**Comment by mpekaross** [comment]
This isn't mandatory for now. Optimization supporting more games and performance improvements, are more important for now.

**Comment by lynxnb** [comment]
Streaming a real-time application like you described is simply impossible, just look at the performance hit recording the screen incurs alone, imagine having to send over the network to another client. The closest thing to this would be LDN support (which we plan to support in the future), or local multiplayer over LAN (this should be supported).
