### ISSUE TITLE
BioShock Remastered

### ISSUE THREAD

**Issue by Gamelover7825** [strato-emu/strato#49]
BioShock Remastered crashes every minute due to memory leak issue.

I'm looking for a way to play BioShock on Android for a very long time.
1) my device is stock, Mi Pad 5 6/256, rooting or anyway modifying the firmware for one-two games is stupid.
2) the PC version on ExaGear immediately freezes on midrange Snapdragon SoCs, and on Termux+Box86+Wine it boots up for a very long time
3) the J2ME/BREW versions lack thousands of things that are present on console and PC versions

**Comment by DominikNovosel** [comment]
If you're sure it's because of a memory leak, try closing all background apps, running your device's RAM cleaner and enabling "Free Guest Texture Memory" in Strato's settings.

**Comment by yuraPIMENOV** [comment]
> If you're sure it's because of a memory leak, try closing all background apps, running your device's RAM cleaner and enabling "Free Guest Texture Memory" in Strato's settings.

I tried everything, free texture memory, direct memory input, closing background apps, and Bioshock still crashes every 3-5 minutes which is very annoying. Will that be fixed in the future? Playing a 2007 game on PC as main way is obsolete, 2023 is not 2014, and other emulators (exagear, box4droid etc) run that game badly on midrange snapdragon chips.

**Comment by DominikNovosel** [comment]
> Bioshock still crashes every 3-5 minutes which is very annoying.

Apparently it's broken on more powerful hardware too: https://github.com/skyline-emu/skyline-games-list/issues/1372


> Will that be fixed in the future?

Probably, that's kinda how software dev works. Support for graphically intensive titles is still not great across the board. I was able to get things like INSIDE to run well, but it's really hit-or-miss.

> other emulators (exagear, box4droid etc) run that game badly on midrange snapdragon chips

Even for Strato/Skyline, in my experience, a near-flagship device is the minimum requirement for getting decent performance in  all but the most undemanding games.

**Comment by Crytonics** [comment]
Closing because we have repository for game-specific issues, go to the [Strato's Compatibility List](https://github.com/strato-emu/compat-list) and report the issue there.
