### ISSUE TITLE
Add option to hide touch controls automatically when external gamepad is connected

### ISSUE THREAD

**Issue by DominikNovosel** [strato-emu/strato#50]
Example implementation in AetherSX2:

![Screenshot_20230615_135426](https://github.com/strato-emu/strato/assets/66269443/2fec27cd-ff59-4064-a821-50866ea2b455)

**Comment by Intelparcel** [comment]
![Screenshot_20230616-010441-edit-20230616010620](https://github.com/strato-emu/strato/assets/132586590/b645986f-7be0-4d4b-a41f-9010f14ae47a)
Well you can toggle it off manually in the controller settings. Maybe the mod could implement this. I know this feature is good, but doing it manually would take like...5 seconds? In my opinion, I just don't think there's enough to implement it into the emulator

**Comment by lynxnb** [comment]
This is a good suggestion, we'll keep it into consideration.
