### ISSUE TITLE
add feature to move pause emu button in touch screen mapping control

### ISSUE THREAD

**Issue by ikhoeyZX** [strato-emu/strato#56]
when playing in touch screen mode, sometimes pause button got pressed

it can't be moved and very frustated when button got mapped to upper right, sometimes pause button get hit and make game crash

**Comment by Crytonics** [comment]
There will be option to disable it in settings.

**Comment by lynxnb** [comment]
Additionally, once we have an in-game menu, the button will entirely be removed from the OSD.
