### ISSUE TITLE
Add support usb controller

### ISSUE THREAD

**Issue by ikhoeyZX** [strato-emu/strato#60]
my controller didn't detect in skyline (no prompt use "wireles device as controller input")
but when using bt mode, my controller detected (my controller have problem that always disconnect after 3 minute when bt mode in android 13

so can strato add this feature (usb controller support)?

like this:
![Screenshot_20230705_194157](https://github.com/strato-emu/strato/assets/79812109/8cf882c7-1ce3-483c-a0c9-a47711d538c9)

**Comment by Intelparcel** [comment]
I have 2 controllers. One is Xbox 360 controller and the other is the Dualshock 4. I tried to connect the 360 controller using usb otg connection and it worked flawlessly. Maybe the controller got some problem? Or maybe it's your phone idk

**Comment by Omarpuche7** [comment]
I think the problem is your device.  With the ps5 controls I have no problems via usb.

**Comment by Intelparcel** [comment]
Please close this issue. This issue is not from Strato
